#pragma once

enum CompEvents
{
	EVENT_NONE,
	EVENT_JUMPED,
	EVENT_STARTEDMOVING,
	EVENT_STOPPEDMOVING,
	EVENT_STARTEDIDLING,
	EVENT_SPAWNED,
	EVENT_DIED,
	EVENT_RESURRECTED,
	EVENT_STARTEDCOLLIDING,
	EVENT_ENDEDCOLLIDING,
	EVENT_COLLIDED,
	EVENT_TOOKDAMAGE,
	EVENT_OBJECTREMOVED,
	EVENT_DEALTHDAMAGE,
	EVENT_FIRED
};

